package com.sample
 
import com.sample.DroolsTest.Message;

/**
* for more information about "ActivationGroup", please read following document. JBoss
* Rules 5 Reference Guide 5.7.
* https://access.redhat.com/site/documentation/en-US/JBoss_Enterprise_BRMS_Platform/5/html-single/JBoss_Rules_5_Reference_Guide/index.html#ActivationGroup
*/
rule "Hello World from group1"
    activation-group "group1"
    salience 150
    when
        m : Message( status == Message.HELLO, myMessage : message )
    then
        System.out.println("rule name : " + kcontext.getRule().getName() );
end

rule "GoodBye from group1"
    activation-group "group1"
    salience 50
    when
        Message( status == Message.HELLO, myMessage : message )
    then
        System.out.println("rule name : " + kcontext.getRule().getName() );
end

rule "Hello World from group2"
    activation-group "group2"
    salience 50
    when
        Message( status == Message.HELLO, myMessage : message )
    then
        System.out.println("rule name : " + kcontext.getRule().getName() );
end

rule "GoodBye from group2"
    activation-group "group2"
    salience 100
    when
        Message( status == Message.HELLO, myMessage : message )
    then
        System.out.println("rule name : " + kcontext.getRule().getName() );
end